[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "4iTkCvhwbbYUvobnobkFN3LkDRiZm1yZoCtvTD2wsKnG"

[programs.devnet]
counter = "4iTkCvhwbbYUvobnobkFN3LkDRiZm1yZoCtvTD2wsKnG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "vitest"
